### ISSUE TITLE
AutoBoot + usbmc

### ISSUE THREAD

**Issue by fwannmacher** [Rinnegatamante/AutoBoot#4]
I have a PSTV and I use [usbmc](https://github.com/yifanlu/usbmc) for setting an external HDD as ux0. But when I try to use AutoBoot the startup always fails and the PSTV shuts down

**Comment by fwannmacher** [comment]
The same is true for [PSVita-StorageMgr](https://github.com/CelesteBlue-dev/PSVita-StorageMgr)

**Comment by CelesteBlue-dev** [comment]
Is enso installed on your PSTV? If so, it might be a time-of-use time-of-check issue.

I might see two workarounds:

1)
https://github.com/Rinnegatamante/AutoBoot/blob/master/main.c#L28
Here change from ux0 to ur0 so that the config can be read even when ux0 is not mounted yet.
But it will likely not be sufficient if your configuration file tells AutoBoot to load applications from ux0...

2)
https://github.com/Rinnegatamante/AutoBoot/blob/master/main.c#L26
Increase this delay value so that usbmc/StorageMgr gets time to mount ux0 before AutoBoot tries to launch an application from ux0.

Edit, compile, test and report please.

**Comment by fwannmacher** [comment]
I think the solution 2 is the best one but I think that tweaking the delay isn't the best approach. The ideal solution would be checking if ux0 is mounted or not and setting a retry mechanism for that.
I was checking the SDK and I didn't find anything for checking ux0. Do you know if is there such function? I'm asking because I think that sceIoOpen is breaking the app so using it for checking ux0 won't work.

**Comment by fwannmacher** [comment]
Maybe sceAppMgrGetDevInfo does the trick.

**Comment by fwannmacher** [comment]
It looks like the issue is not related to ux0 being mounted or not. It seems that AutoBoot is trying to launch the app before the loading is finished.
If I use sceAppMgrGetDevInfo nothing changes but if I increase the delay then it works. The question: how to know that the app can be launched reliably?

**Comment by fwannmacher** [comment]
I wonder if is there a way to check if the livearea is up and running so the app could be launched based on that.

**Comment by Rinnegatamante** [comment]
There probably are better ways to do the whole boot of the app starting with.
This plugin has been made in "ancient" times when knowledge about Vita OS was way limited than it is now.

**Comment by fwannmacher** [comment]
Just to report my findings by adding logs:
- boot.cfg is opened and read without problem
- sceAppMgrLaunchAppByUri returns 0

The behavior is that the loading screen before entering the livearea freezes and the system turns off

**Comment by fwannmacher** [comment]
I have found a solution. NPXS10079 is launched with the livearea so we can check for it. I'll clean the code and then push a PR.

**Comment by fwannmacher** [comment]
https://github.com/Rinnegatamante/AutoBoot/pull/5
